#### **Introduction:**
The entertainment industry has undergone revolutionary transformation in recent years, with data-driven decision-making emerging as the cornerstone of succcess in film production. Companies like Netflix, Amazon Studios and A24 have demonstrated that combining creative vision with rigorous statistical analysis produces superior outcomes compared to solely relying on industry conventions and gut feeling.

Netflix's groundbreaking approach serves as a powerful case study.When the company greenlit House of Cards, it was not based on traditional pitch meetings or gut feelings. Instead, their decisions were informed by comprehensive data showing that audiences who enjoyed political dramas also demonstrated strong preferences for both David Fincher's directorial style and Kevin Spacey's performance. This data-driven methodology proved remarkably successful, validating the prower of analytics in content creation. Similarly, studios like Bluumhouse have revolutionized the horror gene by identifying the optimal budget-to-revenue model, producing critically acclaimed films with budgets under $5 milllion that generates returns exceeding 100%.

As **YE Studios** enters this competitive landscape, we face the same challenge industry leaders such as Netflix overcame i.e. how to translate vast amounts of data into actionable insights that drive commercial success. This project delves into the inticrate world cinema, examining the factors that transform films into box office hits. By analyzing how genre, budget, runtime, ratings, amd studio strategies interact to influence global film revenue, we will uncover patterns that will aid **YE Studio's** future in the industry. Our analysis aims in transalating complex data into clear, actionable recommendations for our new movie studio.

#### **Business Understanding:**
The film industry represents a high-risk, high-reward business environment where production decisions regarding genre, budget, and target audience can determine whether a film becomes a financial dissapointment or a blockbuster. Thererfore, for **YE Studios**, data-driven decisions are not optional but essential for success and survival.

Although, Traditional studios often face challenges from streaming giants such as Netflix who leverage massive user datasets, independent studios like Blumhouse and A24 have proven that smaller, smarter investments can also yield extraordinary returns. Therefore, while navigating this new space,**YE Studios** should aim to position itself strategically,identifying opportunities where data reveals market gaps or untappped potential.

This project aims to provide data-validated answers to critical business questions that will shape the studio's content strategy and market positioning. They include:
- Which genres or specific genre combinations consistently deliver the highest global revenue, and where can we identify underserved niches with lower competition but clear audience demand?
- Do certain genres demonstrate better international appeal, enabling us to maximize global revenue potential?
- What is the optimal budget range for maximum return on investment (ROI)?
- Do independent studios achieve different average ratings compared to major studios, and what can we learn about the indie versus blockbuster strategy?
- How do different financial levels correlate with average ratings and commercial success?
- Does critical acclaim directly correlate with commercial success?
- Does marketing and popularity directly correlate with total gross revenue, and how can we exploit this relationship?
- How do domestic versus foreign markets respond differently to various genres, and should we develop region-specific content strategies?
- What seasonal or temporal patterns exist in box office performance across different genres?

Answering these questions gives **YE Studios** a data-validated playbook for content investment where an evidence-based approach positions us to compete effectively against established industry players while minimzing financial risk and maximizing our probability of creating both critically and acclaimed and commercially successful films.

#### **Data Understanding:**
Our analysis integrates five comprehensive industry-standard datasets. Each source provides unique insights that, when combined, create a holistic view of the factors driving box office success. They include:

**IMDB Database:**
The Internet Movie Database(IMDB) represents the film industry's most comprehensive and trusted repository of movie information, maintained by Amazon and used by professionals worldwide.

Key Variables include:
- Title: Movie names for merging datasets
- Genre: Primary categorization (Action, Drama, Comedy, Horror, etc.)
- Average Rating: User ratings on a 1-10 scale, representing audience satisfaction
- Number of Votes: Volume of user engagement, serving as a popularity metric
- Runtime: Film length in minutes
- Release Year: Temporal data for trend analysis

IMDB's audience sentiment data parallels Netflix's viewing completion and rating metrics. The number of votes serves as a proxy for marketing reach and cultural impact, while average ratings indicate quality perception. This combination allows us to analyze the relationship between popularity, quality, and commercial performance.

**Box Office Mojo:**
Box Office Mojo, also owned by Amazon, provides the definitive source for theatrical revenue tracking, offering detailed financial performance data that forms the core of our commercial analysis.

Key Variables Include:
- Title: Movie identification for data integration
- Studio: Production company responsible for the film
- Domestic Gross: Box office revenue from United States and Canada markets
- Foreign Gross: International box office revenue from all other territories
- Release Date: Launch timing for seasonal analysis

The separation of domestic and foreign revenue is critical for developing a global content strategy. This data reveals which genres travel well internationally, helping Nexus Studios determine whether to focus on domestic-centric content or invest in films with universal appeal. Studio attribution also enables competitive benchmarking against both major and independent players.

**Rotten Tomatoes:**
Rotten Tomatoes provides dual perspectives on film quality through both professional critic scores and verified audience ratings, offering insights into critical versus commercial apppeal.

Key Variabes include:
- Synopsis: Plot summaries for contextual understanding
- Rating: Content rating (PG, PG-13, R, etc.) indicating target audience
- Genre: Genre classification for cross-validation with IMDB data
- Director and Writer: Creative leadership information
- Theater Date and DVD Date: Release strategy timing
- Box Office: Revenue figures for validation against Box Office Mojo data
- Runtime: Film length for analysis consistency
- Studio: Production company for comprehensive studio analysis

Rotten Tomatoes' unique contribution is the critical reception data, which helps identify whether films succeed through quality (critic-approved) or pure commercial appeal (audience-driven). 

**TheMovieDB(TMDB):**
The Movie DB is a community-built database that provides extensive metadata on films including deatiled production information,genre classifications, and popularity metrics based on user engagement.

Key Variables include:
- Title and Original Title: Movie identification in different languages
- Genre IDs: Detailed genre categorization for cross-validation
- Popularity Score: Real-time engagement metric based on views, votes, and user interactions
- Vote Average and Vote Count: Community ratings for quality assessment
- Release Date: Timing information for temporal analysis
- Original Language: Language of production for international market analysis

TMDB's popularity score provides a unique, real-time measure of audience interest that complements traditional box office data. This helps identify trending films and emerging genre preferences before they're fully reflected in revenue figures. The detailed genre tagging also enables more nuanced analysis of genre combinations and hybrid categories.

**The Numbers:**
The Numbers specializes in comprehensive financial data for the film industry, providing detailed budget information and production cost analysis that other sources often lack.

Key Variables Include:
- Title: Movie identification for dataset integration
- Production Budget: Actual production costs for ROI calculations
- Domestic Gross and Worldwide Gross: Box office revenue for profitability analysis
- Release Date: Temporal information for trend analysis
- Genre: Genre classification for comparative analysis

The Numbers' production budget data is crucial for calculating true return on investment (ROI), which is often more relevant than gross revenue alone. This enables YE Studios to identify which genres and budget ranges offer the best profit margins, not just the highest revenue. The budget-to-revenue ratio analysis helps determine the minimum viable investment for different film categories.

#### **Data Integration:**
These datasets will be merged using movie titles as the common identifier, creating a comprehensive database that links financial performance (Box Office Mojo, The Numbers), audience sentiment (IMDB, TMDB), and critical reception (Rotten Tomatoes). This multi-source mirrors how streaming platforms combine diverse data streams to inform content decisions.

Key Integration Considerations:
- Title Matching: Standardizing movie names across datasets to ensure accurate merging,handling variations in international titles.
- Data Cleaning: Handling missing values, duplicates, and inconsistent formatting.
- Genre Harmonization: Reconciling different genre classification systems.
- Revenue Normalization: Accounting for inflation and currency differences.
- Budget Data Vaidation: Cross-checking production budget figures from The Numbers Data gaianst revenue data.
- Temporal Alignment: Ensuring release dates and financial data correspond correctly.

By combining these five authoritative sources, we create a dataset with sufficient breadth and depth to answer our business questions rigorously by enabling us to carry out a multidimensional analysis examining how genre, budget, runtime, ratings, and studio characteristics interact to influence commercial success.

#### **DATA CLEANING:**

In [2]:
#Loading the Data and important librarioes.
import numpy as np
import pandas as pd
import gzip

tndb = pd.read_csv("../data/zippedData/tn.movie_budgets.csv.gz", compression= "gzip")
tndb.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"

In [3]:
#CLEANING THE DATA:
#Cleaning the column names lowercase and replace spaces with underscores and remove parathenses.
tndb.columns = tndb.columns.str.strip().str.lower().str.replace(" ","_").str.replace("(","").str.replace(")","")
tndb.head()
tndb.dtypes

id                    int64
release_date         object
movie                object
production_budget    object
domestic_gross       object
worldwide_gross      object
dtype: object

In [4]:
#CLEAN DATES:
#Convert release date to datetime formart.
tndb["release_date"]= pd.to_datetime(tndb["release_date"], errors = "coerce")

#Extract year for analysis:
tndb["release_year"]= tndb["release_date"].dt.year
tndb.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,release_year
0,1,2009-12-18,Avatar,"$425,000,000","$760,507,625","$2,776,345,279",2009
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875",2011
2,3,2019-06-07,Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350",2019
3,4,2015-05-01,Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963",2015
4,5,2017-12-15,Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747",2017

In [5]:
#CLEAN MOVIE TITLES:
#Remove extra whitespace from movie titles.
tndb["movie"] = tndb["movie"].str.strip()
tndb.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,release_year
0,1,2009-12-18,Avatar,"$425,000,000","$760,507,625","$2,776,345,279",2009
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875",2011
2,3,2019-06-07,Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350",2019
3,4,2015-05-01,Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963",2015
4,5,2017-12-15,Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747",2017

In [6]:
#CLEAN FINACIAL DATA:
#Remove $ sign and convert to numeric.
tndb["production_budget"]= tndb["production_budget"].str.replace("$","").str.replace(",","")
tndb["production_budget"] = pd.to_numeric(tndb["production_budget"], errors="coerce")


tndb["domestic_gross"]= tndb["domestic_gross"].str.replace("$","").str.replace(",","")
tndb["domestic_gross"] = pd.to_numeric(tndb["domestic_gross"], errors="coerce")


tndb["worldwide_gross"]= tndb["worldwide_gross"].str.replace("$","").str.replace(",","")
tndb["worldwide_gross"] = pd.to_numeric(tndb["worldwide_gross"], errors="coerce")

tndb.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,release_year
0,1,2009-12-18,Avatar,425000000,760507625,2776345279,2009
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011
2,3,2019-06-07,Dark Phoenix,350000000,42762350,149762350,2019
3,4,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015
4,5,2017-12-15,Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017

In [7]:
#CREATE NEW COLUMNS:
#Calcuate profit
tndb["profit"]= tndb["worldwide_gross"]- tndb["production_budget"]

#Calculate return on investement(ROI)
tndb["roi"] = (tndb["profit"] / tndb["production_budget"] * 100)

#Calulate profit margin
tndb["foreign_gross"]= tndb["worldwide_gross"]- tndb["domestic_gross"]

tndb.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,release_year,profit,roi,foreign_gross
0,1,2009-12-18,Avatar,425000000,760507625,2776345279,2009,2351345279,553.257713,2015837654
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,635063875,154.667286,804600000
2,3,2019-06-07,Dark Phoenix,350000000,42762350,149762350,2019,-200237650,-57.210757,107000000
3,4,2015-05-01,Avengers: Age of Ultron,330600000,459005868,1403013963,2015,1072413963,324.384139,944008095
4,5,2017-12-15,Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017,999721747,315.369636,696540365

In [8]:
#HANDLE DUPLICATES AND REMOVE MISSING VALUES:
#Sort by worldwide_gross and keep highest grosssing movie for each title.
tndb = tndb.sort_values("worldwide_gross", ascending= False)
tndb = tndb.drop_duplicates(subset= "movie", keep = "first")

#Drop rows where budget or worldwide_gross is missing
tndb = tndb.dropna(subset=["production_budget", "worldwide_gross"])
tndb.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,release_year,profit,roi,foreign_gross
0,1,2009-12-18,Avatar,425000000,760507625,2776345279,2009,2351345279,553.257713,2015837654
42,43,1997-12-19,Titanic,200000000,659363944,2208208395,1997,2008208395,1004.104198,1548844451
5,6,2015-12-18,Star Wars Ep. VII: The Force Awakens,306000000,936662225,2053311220,2015,1747311220,571.016739,1116648995
6,7,2018-04-27,Avengers: Infinity War,300000000,678815482,2048134200,2018,1748134200,582.711400,1369318718
33,34,2015-06-12,Jurassic World,215000000,652270625,1648854864,2015,1433854864,666.909239,996584239

In [9]:
##FINAL CHECK OF CLEANED DATA:
#View cleaned data
tndb.head()
#Check for any remaining missing values
tndb.isnull().sum()
#Check for any remaining duplicates
tndb.duplicated(subset="movie").sum()

0